version: "2"
services:
    web:
        build: passenger
        volumes:
            - ./passenger/ssl:/etc/ssl/private
            - ./passenger/sites-available:/etc/nginx/sites-available
            - ../api:/home/app/api
            #- ../frontend/dist:/home/app/html
        ports:
            - 80:80
            - 443:443
